### ISSUE TITLE
.NET Framework 4.6.1 dependency System.Net.NameResolution

### ISSUE THREAD

**Issue by rodrigolck** [DataDog/dogstatsd-csharp-client#84]
Hello there!

I was wondering why .NET Framework 4.5.1 doesn't have the dependency System.Net.NameResolution and 4.6.1 has. So, I forked the project and tried to build 4.6.1 without the dependency from System.Net.NameResolution and it worked.
Is there any reason why there is this dependency?

Best regards,

**Comment by ogaca-dd** [comment]
Apologies for the delay @rodrigolck

At least for now, there is no reason to have this dependency for .NET framework and it was fixed by https://github.com/DataDog/dogstatsd-csharp-client/pull/92.
```
  <ItemGroup Condition="'$(TargetFramework)' != 'net451' AND '$(TargetFramework)' != 'net461'">
    <PackageReference Include="System.Net.NameResolution">
      <Version>4.3.0</Version>
    </PackageReference>
  </ItemGroup>
```

Nuget package [4.0.0](https://www.nuget.org/packages/DogStatsD-CSharp-Client/4.0.0) has no dependencies for the .NET Frameworks.

Best regards,
